controllers:
    resource: ../../src/Controller/
    type: annotation

calendar:
    resource: ../../src/Calendar/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
